[package]
name = "templates"
version = "1.0.0"
description="A CLI tool to manage templates from the VSCode Extension 'Project Templates' (cantonios.project-templates)"
edition = "2021"

[dependencies]
dirs = "4.0.0"
walkdir = "2.3.2"
